# Generated by Django 3.1.7 on 2021-04-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('desc', models.TextField()),
                ('categ', models.TextField()),
                ('period', models.TextField()),
                ('hour', models.TextField()),
                ('website', models.TextField()),
                ('mainpic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('clap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_store', to='server.store')),
            ],
        ),
        migrations.CreateModel(
            name='Bigmarket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_store', to='server.store')),
            ],
        ),
    ]
