# Generated by Django 3.1.7 on 2021-03-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('desc', models.TextField()),
                ('mainpic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('clap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.TextField()),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('store', models.ManyToManyField(blank=True, to='server.Store')),
            ],
        ),
    ]
