# Generated by Django 3.1.7 on 2021-04-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigmarket',
            name='store',
        ),
        migrations.AddField(
            model_name='bigmarket',
            name='store',
            field=models.ManyToManyField(blank=True, to='server.Store'),
        ),
    ]
