# Generated by Django 3.1.7 on 2021-04-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210409_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('store', models.ManyToManyField(blank=True, to='server.Store')),
            ],
        ),
    ]
