# Generated by Django 3.1.7 on 2021-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210411_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='store',
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
